import { CAC } from 'cac';
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import type { CommandContext } from '../../types.js';
import { HOOK_COMMANDS, OPENCODE_SCHEMA_URL, REQUIRED_INSTRUCTION_ENTRIES } from '../../constant.js';
import {
  type BasePaths,
  getBasePaths,
  initPublic,
  fileExists,
  readJsonFile,
  writeJsonFile,
} from './initPublic.js';

// =============================================================================
// OpenCode-Specific Types
// =============================================================================

interface OpencodeConfig {
  $schema?: string;
  instructions?: string[];
  plugin?: string[];
  [key: string]: unknown;
}

interface OpencodePaths extends BasePaths {
  opencodeDir: string;
  pluginsDir: string;
  pluginPath: string;
  opencodeConfigPath: string;
}

export interface OpencodeSetupResult {
  pluginWritten: boolean;
  configUpdated: boolean;
}

// =============================================================================
// OpenCode Plugin Template
// =============================================================================
//
// This file is copied to `<cwd>/.opencode/plugins/memory-anchor.js`.
// OpenCode auto-loads anything in `.opencode/plugins/` and exposes `$`
// (Bun's shell API) for spawning child processes — which we use to call
// the published `memoryanchor-opencode-*` CLI hooks.

const OPENCODE_PLUGIN_BODY = `// Auto-generated by Memory Anchor. Do not edit by hand.
import { $ } from "bun";

const HOOK_BIN = "${HOOK_COMMANDS.OPENCODE}";

function run(name, args = []) {
  // Fire-and-forget; we never block opencode on hook output.
  const cmd = \`\${HOOK_BIN}-\${name} \${args.join(" ")}\`.trim();
  $\`\${cmd}\`.catch(() => {
    // Swallow errors — hooks should never break the agent loop.
  });
}

export const MemoryAnchorPlugin = async () => {
  return {
    // Session start: dump the memory core payload.
    "session.start": async () => {
      run("pre");
    },
    
    // Session idle (work finished) → incremental chart refresh.
    "session.idle": async () => {
      run("stop");
    },

    // Session deleted (closed/reset) → run session-end.
    "session.deleted": async () => {
      run("post");
    },
  };
};
`;

// =============================================================================
// OpenCode Paths
// =============================================================================

function getOpencodePaths(cwd: string): OpencodePaths {
  const base = getBasePaths(cwd);
  const opencodeDir = path.join(cwd, '.opencode');
  const pluginsDir = path.join(opencodeDir, 'plugins');

  return {
    ...base,
    opencodeDir,
    pluginsDir,
    pluginPath: path.join(pluginsDir, 'memory-anchor.js'),
    opencodeConfigPath: path.join(cwd, 'opencode.json'),
  };
}

// =============================================================================
// Plugin File (.opencode/plugins/memory-anchor.js)
// =============================================================================

async function ensurePluginFile(paths: OpencodePaths): Promise<boolean> {
  await mkdir(paths.pluginsDir, { recursive: true });

  const exists = await fileExists(paths.pluginPath);
  if (exists) {
    // Never silently overwrite — user may have customized the plugin.
    return false;
  }

  await writeFile(paths.pluginPath, OPENCODE_PLUGIN_BODY, 'utf8');
  return true;
}

// =============================================================================
// opencode.json
// =============================================================================
//
// We only manage two keys we own:
//   - `$schema`: pinned for editor autocomplete
//   - `instructions`: prepended with our anchor files (AGENTS.md + memory core)
// Other keys (model, provider, mcp, …) are left untouched / merged.

async function ensureOpencodeConfig(paths: OpencodePaths): Promise<boolean> {
  const exists = await fileExists(paths.opencodeConfigPath);
  if (!exists) {
    const config: OpencodeConfig = {
      $schema: OPENCODE_SCHEMA_URL,
      instructions: [...REQUIRED_INSTRUCTION_ENTRIES],
    };
    await writeJsonFile(paths.opencodeConfigPath, config);
    return true;
  }

  const config = await readJsonFile<OpencodeConfig>(paths.opencodeConfigPath);
  const updated = mergeOpencodeConfig(config);

  if (updated) {
    await writeJsonFile(paths.opencodeConfigPath, config);
  }

  return updated;
}

function mergeOpencodeConfig(config: OpencodeConfig): boolean {
  let updated = false;

  if (config.$schema == null) {
    config.$schema = OPENCODE_SCHEMA_URL;
    updated = true;
  }

  if (!Array.isArray(config.instructions)) {
    config.instructions = [];
    updated = true;
  }

  // Prepend our required entries, skipping ones already present (substring
  // match so "./AGENTS.md" matches "AGENTS.md" and vice-versa).
  for (const entry of REQUIRED_INSTRUCTION_ENTRIES) {
    const alreadyPresent = config.instructions!.some(
      (existing) =>
        existing === entry ||
        existing.endsWith(entry.replace(/^\.\//, '')) ||
        entry.endsWith(existing.replace(/^\.\//, '')),
    );
    if (!alreadyPresent) {
      config.instructions!.unshift(entry);
      updated = true;
    }
  }

  return updated;
}

// =============================================================================
// Standalone OpenCode Setup
// =============================================================================

export async function opencodeSetup(cwd: string): Promise<OpencodeSetupResult> {
  const paths = getOpencodePaths(cwd);

  const pluginWritten = await ensurePluginFile(paths);
  const configUpdated = await ensureOpencodeConfig(paths);

  return { pluginWritten, configUpdated };
}

// =============================================================================
// Command Registration
// =============================================================================

export function initOpencodeCommand(cli: CAC, context: CommandContext): void {
  cli
    .command('init-opencode', 'Initialize OpenCode MemoryAnchor workspace')
    .action(async () => {
      const cwd = process.cwd();

      const common = await initPublic(cwd);
      const specific = await opencodeSetup(cwd);

      if (
        common.gitignoreUpdated ||
        common.anchorFilesCreated ||
        common.agentsCreated ||
        specific.pluginWritten ||
        specific.configUpdated
      ) {
        context.logger.info(
          'Memory anchor initialized for OpenCode in ./.memoryanchor and ./.opencode',
        );
      } else {
        context.logger.info(
          'Memory anchor for OpenCode already exists in ./.memoryanchor and ./.opencode',
        );
      }
    });
}
